---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: require-pod-security-admission
spec:
  enforcementAction: warn  # deny
  match:
    excludedNamespaces:
      - 'kube-*'
      - '*argocd*'
      - '*gatekeeper-system*'
    kinds:
      - apiGroups:
         - ""
        kinds:
          - Namespace
  parameters:
    message: "All namespaces must have an Pod Security Admission labels set: ['pod-security.kubernetes.io/enforce: restricted', 'pod-security.kubernetes.io/enforce-version: v1.27']"
    labels:
      - key: pod-security.kubernetes.io/enforce
        allowedRegex: restricted
      - key: pod-security.kubernetes.io/enforce-version
        allowedRegex: v1.27

---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata:
  name: container-must-have-limits
spec:
  enforcementAction: warn  # deny
  match:
    scope: Cluster
    excludedNamespaces:
      - 'kube-*'
      - '*argocd*'
      - '*gatekeeper-system*'
    kinds:
      - apiGroups:
         - ""
        kinds:
          - Namespace
  parameters: {}

---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerRequests
metadata:
  name: container-must-have-requests
spec:
  enforcementAction: warn  # deny
  match:
    scope: Cluster
    excludedNamespaces:
      - 'kube-*'
      - '*argocd*'
      - '*gatekeeper-system*'
    kinds:
      - apiGroups:
         - ""
        kinds:
          - Namespace
  parameters: {}
