apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secure-pod.yml
  - ./constraints/pod-security-admission.yaml
  - ./constraints/container-limits.yaml
  - ./constraints/container-requests.yaml
  - ./constraints/require-pod-security-admission.yaml
